global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.188.130:9090']
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:9000']
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']


